"""
Django settings for crm project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from decouple import Csv, config
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='', cast=Csv())


# Application definition

INSTALLED_APPS = [
    
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'django_filters',
    'channels',
    'authentication',
    'base',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'course',
    'enrollment',
    'counselling',
    'skill',
    'career',
    'assessment',
    'drf_yasg',
    'django_celery_results',
    'dashboard',
    'notifications',
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'student_guidance_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'student_guidance_system.wsgi.application'
ASGI_APPLICATION = 'student_guidance_system.asgi.application'

# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             'hosts': [config('CELERY_BROKER_URL', default='redis://192.168.251.9:6379/0')],
#         },
#     },
# }

# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [
#                 "redis://redis:6379/2"
#                 ],
            
#         },
#     },
# }

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DB_ENGINE = config('DB_ENGINE', default='django.db.backends.sqlite3')
# DB_NAME = config('DB_NAME', default='db.sqlite3')

# if DB_ENGINE == 'django.db.backends.sqlite3':
#     DATABASES = {
#         'default': {
#             'ENGINE': DB_ENGINE,
#             'NAME': BASE_DIR / DB_NAME,
#         }
#     }
# else:
#     DATABASES = {
#         'default': {
#             'ENGINE': DB_ENGINE,
#             'NAME': DB_NAME,
#             'USER': config('DB_USER', default=''),
#             'PASSWORD': config('DB_PASSWORD', default=''),
#             'HOST': config('DB_HOST', default=''),
#             'PORT': config('DB_PORT', default=''),
#         }
#     }

#for render db conn
import dj_database_url

DATABASES = {
    "default": dj_database_url.config(
        default=config("DATABASE_URL")
    )
}

REDIS_URL = config("REDIS_URL")

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                f"{REDIS_URL}/0"
            ],
            "capacity": 1500,
            "expiry": 10,
        },
    },
}


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"{REDIS_URL}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
        "KEY_PREFIX": "sgs",
        "TIMEOUT": 300,
    }
}


CELERY_BROKER_URL = f"{REDIS_URL}/2"
CELERY_RESULT_BACKEND = "django-db"


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

AUTH_USER_MODEL = 'authentication.User'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 5,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
}

SESSION_COOKIE_NAME = "sessionid"
SESSION_COOKIE_HTTPONLY = True          # JavaScript cannot read
# SESSION_COOKIE_SECURE = False            # HTTPS only in production
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = "Strict"          # "None" requires Secure=True (HTTPS), else browsers reject the cookie
SESSION_COOKIE_AGE = 1209600             # 2 weeks in seconds
SESSION_SAVE_EVERY_REQUEST = True      # Refresh expiry on activity

# ===================================================================
# 3. CSRF Protection (for browsable API / admin)
# ===================================================================
CSRF_COOKIE_HTTPONLY = False   # frontend JS must read this cookie to send X-CSRFToken
# CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = "Lax"


CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', cast=Csv())
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', cast=Csv())

# ===================================================================
# 4. CORS (required for cross-origin frontend)
# ===================================================================

CORS_ALLOW_CREDENTIALS = True   # Allow cookies in cross-origin requests

# CACHES = {
#     'default': {
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': 'redis://redis:6379/1',
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#         },
#         'KEY_PREFIX': 'skillshikshya',
#         'TIMEOUT': 300,
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = config('LANGUAGE_CODE', default='en-us')

TIME_ZONE = config('TIME_ZONE', default='UTC')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'
STATIC_ROOT = BASE_DIR / "staticfiles"


# REDIS_HOST = config('REDIS_HOST', default='redis')
# REDIS_PORT = config('REDIS_PORT', default='6379')
# REDIS_DB = config('REDIS_DB', default='0')
# REDIS_PASSWORD = config('REDIS_PASSWORD', default='')  # Empty string if not set

# redis_url = f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}'

# CELERY_BROKER_URL = redis_url
# CELERY_RESULT_BACKEND = redis_url

# Other Celery settings (hardcoded in settings.py, not .env)
CELERY_REDIS_MAX_CONNECTIONS = 20
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60



# Optional: Enable extended task information (like task arguments)
CELERY_RESULT_EXTENDED = True
