# Generated by Django 6.0.6 on 2026-08-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('system', 'System'), ('message', 'Message'), ('alert', 'Alert'), ('reminder', 'Reminder')], default='system', max_length=50),
        ),
    ]
